export enum Events {
  NEW_MESSAGE = "new message",
  ENTER_CHANNEL = "enter channel",
  LEAVE_CHANNEL = "leave channel",
  INIT_CHAT = "init chat",
  NEW_GROUP = "new group",
  LIST_GROUPS = "list groups",
  ADD_PLAYER = "add player",
  PLAYER_READY = "player ready",
  LEAVE_GROUP = "leave group",
  STATE_UPDATE = "state update",
  UNSUBSCRIBE = "unsubscribe",
  DRAW = "draw",
  GUESS = "guess",
  CLUE = "clue",
  GAME_FINISHED = "game finished",
  START_VIRTUAL = "start virtual",
  ROUND_FINISHED = "round finished",
  TOURNAMENT_STATE = "tournament state",
  TOURNAMENT_FINISHED = "tournament finished",
}
